# Official framework image.
image: node:latest

# This folder is cached between builds
cache:
  paths:
    - node_modules/

# default stages "build, test, deploy", can also have my own stages which will run in the order
# stages:
#   - build
#   - test

# the job and its name
build-job:
  # which stage to run it
  stage: build
  # specifying the runner to execute the job (in our case it is a docker which is a shared runner in GitLab, you can also configure your own)
  tags:
    - docker
  # execution with env variables
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  tags:
    - docker
  script:
    - echo "This job restaurant something"

test-job2:
  stage: test
  tags:
    - docker
  script:
    - echo "This job restaurant something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  tags:
    - docker
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
